import { useQuery } from '@tanstack/react-query';
import { Package, ShoppingBag, Users, Wallet, TrendingUp, Clock } from 'lucide-react';
import api from '../api';

export default function Home() {
  const { data: stats } = useQuery({
      queryKey: ['stats'],
          queryFn: async () => { const { data } = await api.get('/api/admin/stats-data'); return data; },
            });

              const orders      = stats?.orders      || [];
                const users       = stats?.users       || [];
                  const products    = stats?.products    || [];
                    const withdrawals = stats?.withdrawals || [];

                      const totalRevenue  = orders.filter((o: any) => o.status === 'delivered').reduce((s: number, o: any) => s + (o.totalAmount || 0), 0);
                        const pendingOrders = orders.filter((o: any) => ['pending','processing','preparing','shipping'].includes(o.status)).length;
                          const merchants     = users.filter((u: any) => u.role === 'merchant').length;
                            const pendingW      = withdrawals.filter((w: any) => w.status === 'pending').length;

                              const cards = [
                                  { label: 'إجمالي الطلبات',       value: orders.length,    icon: ShoppingBag, color: 'bg-blue-500',   bg: 'bg-blue-50'   },
                                      { label: 'طلبات نشطة',           value: pendingOrders,    icon: Clock,       color: 'bg-amber-500',  bg: 'bg-amber-50'  },
                                          { label: 'التجار المسجلين',       value: merchants,        icon: Users,       color: 'bg-purple-500', bg: 'bg-purple-50' },
                                              { label: 'المنتجات',             value: products.length,  icon: Package,     color: 'bg-primary',    bg: 'bg-teal-50'   },
                                                  { label: 'سحوبات معلقة',         value: pendingW,         icon: Wallet,      color: 'bg-red-500',    bg: 'bg-red-50'    },
                                                      { label: 'إجمالي المبيعات د.ع', value: totalRevenue.toLocaleString(), icon: TrendingUp, color: 'bg-green-500', bg: 'bg-green-50' },
                                                        ];

                                                          return (
                                                              <div className="p-8">
                                                                    <div className="mb-8">
                                                                            <h1 className="text-2xl font-black text-gray-800">لوحة التحكم</h1>
                                                                                    <p className="text-gray-500 mt-1 text-sm">نظرة عامة على أداء منصة تسليم</p>
                                                                                          </div>

                                                                                                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
                                                                                                        {cards.map(({ label, value, icon: Icon, color, bg }) => (
                                                                                                                  <div key={label} className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
                                                                                                                              <div className="flex items-center justify-between flex-row-reverse">
                                                                                                                                            <div className={`w-12 h-12 ${bg} rounded-xl flex items-center justify-center`}>
                                                                                                                                                            <Icon size={22} className={`${color.replace('bg-', 'text-')}`} />
                                                                                                                                                                          </div>
                                                                                                                                                                                        <div className="text-right">
                                                                                                                                                                                                        <p className="text-3xl font-black text-gray-800">{value}</p>
                                                                                                                                                                                                                        <p className="text-sm text-gray-500 mt-1">{label}</p>
                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                {/* آخر الطلبات */}
                                                                                                                                                                                                                                                                                      <div className="mt-8 bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
                                                                                                                                                                                                                                                                                              <div className="p-6 border-b border-gray-100">
                                                                                                                                                                                                                                                                                                        <h2 className="font-black text-gray-800">آخر الطلبات</h2>
                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                        <div className="overflow-x-auto">
                                                                                                                                                                                                                                                                                                                                  <table className="w-full text-right">
                                                                                                                                                                                                                                                                                                                                              <thead className="bg-gray-50 text-xs text-gray-500 font-semibold">
                                                                                                                                                                                                                                                                                                                                                            <tr>
                                                                                                                                                                                                                                                                                                                                                                            <th className="px-6 py-3">#</th>
                                                                                                                                                                                                                                                                                                                                                                                            <th className="px-6 py-3">الزبون</th>
                                                                                                                                                                                                                                                                                                                                                                                                            <th className="px-6 py-3">المحافظة</th>
                                                                                                                                                                                                                                                                                                                                                                                                                            <th className="px-6 py-3">المجموع</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <th className="px-6 py-3">الحالة</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <tbody className="divide-y divide-gray-50">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {orders.slice(0, 8).map((o: any) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <tr key={o.id} className="hover:bg-gray-50 transition-colors">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td className="px-6 py-4 text-sm font-bold text-gray-500">#{o.id}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td className="px-6 py-4 text-sm font-semibold text-gray-800">{o.customerName || '—'}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <td className="px-6 py-4 text-sm text-gray-500">{o.province || '—'}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td className="px-6 py-4 text-sm font-bold text-primary">{o.totalAmount?.toLocaleString()} د.ع</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td className="px-6 py-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className={`px-3 py-1 rounded-full text-xs font-bold ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    o.status === 'delivered' ? 'bg-green-100 text-green-700' :
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          o.status === 'cancelled' ? 'bg-red-100 text-red-600' :
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'bg-amber-100 text-amber-700'}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {o.status === 'delivered' ? 'مكتمل' :
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             o.status === 'cancelled' ? 'ملغي' :
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    o.status === 'pending'   ? 'معلق' : o.status}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  