import { useState, FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import toast from 'react-hot-toast';

export default function Login() {
  const { login } = useAuth();
    const navigate   = useNavigate();
      const [phone, setPhone]       = useState('');
        const [password, setPassword] = useState('');
          const [loading, setLoading]   = useState(false);

            const handleSubmit = async (e: FormEvent) => {
                e.preventDefault();
                    if (!phone || !password) return toast.error('أدخل رقم الهاتف وكلمة المرور');
                        setLoading(true);
                            try {
                                  await login(phone, password);
                                        toast.success('مرحباً بك في لوحة تسليم');
                                              navigate('/');
                                                  } catch (err: any) {
                                                        toast.error(err?.response?.data?.message || err?.message || 'فشل تسجيل الدخول');
                                                            } finally {
                                                                  setLoading(false);
                                                                      }
                                                                        };

                                                                          return (
                                                                              <div className="min-h-screen bg-gradient-to-br from-[#0a4f5e] via-[#0c6679] to-[#0a8a9f] flex items-center justify-content-center p-4">
                                                                                    <div className="w-full max-w-md mx-auto">

                                                                                            {/* Logo */}
                                                                                                    <div className="text-center mb-8">
                                                                                                              <div className="inline-flex items-center justify-center w-20 h-20 bg-white/20 backdrop-blur rounded-3xl mb-4 border border-white/30">
                                                                                                                          <span className="text-white font-black text-3xl">ت</span>
                                                                                                                                    </div>
                                                                                                                                              <h1 className="text-white font-black text-3xl">تسليم</h1>
                                                                                                                                                        <p className="text-white/70 text-sm mt-1">لوحة الإدارة</p>
                                                                                                                                                                </div>

                                                                                                                                                                        {/* Card */}
                                                                                                                                                                                <div className="bg-white rounded-3xl p-8 shadow-2xl">
                                                                                                                                                                                          <h2 className="text-xl font-black text-gray-800 mb-6 text-right">تسجيل الدخول</h2>

                                                                                                                                                                                                    <form onSubmit={handleSubmit} className="space-y-4">
                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                              <label className="block text-sm font-semibold text-gray-600 mb-2 text-right">رقم الهاتف</label>
                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                            type="tel"
                                                                                                                                                                                                                                                                            value={phone}
                                                                                                                                                                                                                                                                                            onChange={(e) => setPhone(e.target.value)}
                                                                                                                                                                                                                                                                                                            placeholder="07XXXXXXXXX"
                                                                                                                                                                                                                                                                                                                            dir="rtl"
                                                                                                                                                                                                                                                                                                                                            className="w-full px-4 py-3 rounded-2xl border-2 border-gray-100 focus:border-primary outline-none text-right transition-colors text-gray-800 bg-gray-50"
                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                <label className="block text-sm font-semibold text-gray-600 mb-2 text-right">كلمة المرور</label>
                                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                                              type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                              value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              placeholder="••••••••"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              dir="rtl"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full px-4 py-3 rounded-2xl border-2 border-gray-100 focus:border-primary outline-none text-right transition-colors text-gray-800 bg-gray-50"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full bg-primary hover:bg-primary-dark text-white font-bold py-3.5 rounded-2xl transition-all duration-200 mt-2 disabled:opacity-60 disabled:cursor-not-allowed">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {loading ? 'جاري الدخول...' : 'دخول'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-center text-xs text-gray-400 mt-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        يسمح فقط لحسابات الأدمن بالوصول
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      