import { NavLink } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import {
  LayoutDashboard, Package, ShoppingBag, Users,
    Wallet, Tag, Bell, Image, BarChart3, MessageSquare, LogOut, Ticket
    } from 'lucide-react';

    const links = [
      { to: '/',              label: 'الرئيسية',       icon: LayoutDashboard },
        { to: '/products',      label: 'المنتجات',        icon: Package },
          { to: '/orders',        label: 'الطلبات',          icon: ShoppingBag },
            { to: '/merchants',     label: 'التجار',           icon: Users },
              { to: '/withdrawals',   label: 'السحوبات',         icon: Wallet },
                { to: '/categories',    label: 'الفئات',           icon: Tag },
                  { to: '/promos',        label: 'أكواد الخصم',      icon: Ticket },
                    { to: '/banners',       label: 'البنرات',          icon: Image },
                      { to: '/notifications', label: 'الإشعارات',        icon: Bell },
                        { to: '/support',       label: 'الدعم الفني',      icon: MessageSquare },
                          { to: '/stats',         label: 'الإحصائيات',       icon: BarChart3 },
                          ];

                          export default function Sidebar() {
                            const { user, logout } = useAuth();

                              return (
                                  <aside className="w-64 bg-white h-screen flex flex-col border-l border-gray-100 shadow-sm fixed right-0 top-0 z-40">

                                        {/* Logo */}
                                              <div className="p-6 border-b border-gray-100">
                                                      <div className="flex items-center gap-3 flex-row-reverse">
                                                                <div className="w-10 h-10 bg-primary rounded-xl flex items-center justify-center flex-shrink-0">
                                                                            <span className="text-white font-black text-lg">ت</span>
                                                                                      </div>
                                                                                                <div className="text-right">
                                                                                                            <p className="font-black text-gray-800 text-lg leading-none">تسليم</p>
                                                                                                                        <p className="text-xs text-gray-400 mt-0.5">لوحة الإدارة</p>
                                                                                                                                  </div>
                                                                                                                                          </div>
                                                                                                                                                </div>

                                                                                                                                                      {/* User info */}
                                                                                                                                                            <div className="px-4 py-3 mx-3 mt-3 bg-primary/5 rounded-2xl border border-primary/10">
                                                                                                                                                                    <p className="text-right text-sm font-bold text-gray-700 truncate">{user?.storeName}</p>
                                                                                                                                                                            <p className="text-right text-xs text-primary font-semibold">أدمن</p>
                                                                                                                                                                                  </div>

                                                                                                                                                                                        {/* Nav */}
                                                                                                                                                                                              <nav className="flex-1 overflow-y-auto px-3 py-4 space-y-1">
                                                                                                                                                                                                      {links.map(({ to, label, icon: Icon }) => (
                                                                                                                                                                                                                <NavLink
                                                                                                                                                                                                                            key={to}
                                                                                                                                                                                                                                        to={to}
                                                                                                                                                                                                                                                    end={to === '/'}
                                                                                                                                                                                                                                                                className={({ isActive }) =>
                                                                                                                                                                                                                                                                              `flex items-center gap-3 flex-row-reverse px-4 py-2.5 rounded-xl text-sm font-semibold transition-all duration-150 ${
                                                                                                                                                                                                                                                                                              isActive
                                                                                                                                                                                                                                                                                                                ? 'bg-primary text-white shadow-sm'
                                                                                                                                                                                                                                                                                                                                  : 'text-gray-600 hover:bg-gray-50 hover:text-gray-800'
                                                                                                                                                                                                                                                                                                                                                }`
                                                                                                                                                                                                                                                                                                                                                            }>
                                                                                                                                                                                                                                                                                                                                                                        <Icon size={18} />
                                                                                                                                                                                                                                                                                                                                                                                    <span>{label}</span>
                                                                                                                                                                                                                                                                                                                                                                                              </NavLink>
                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                            </nav>

                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Logout */}
                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="p-3 border-t border-gray-100">
                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={logout}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full flex items-center gap-3 flex-row-reverse px-4 py-2.5 rounded-xl text-sm font-semibold text-red-500 hover:bg-red-50 transition-all">
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <LogOut size={18} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span>تسجيل الخروج</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </aside>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            